media: docs/.vuepress/public
content:
  - name: notes
    label: 笔记
    type: collection
    path: 'docs/notes'
    view:
      fields: [ title, tags ]
    fields:
      - name: title
        label: 标题
        type: string
      - name: tags
        label: 标签
        type: string
      - name: createTime
        label: 创建时间
        type: date
        options:
          format: yyyy-MM-dd HH:mm:ss
  - name: preview
    label: 随记
    type: collection
    path: 'docs/preview'
    view:
      fields: [ title, tags ]
      search: [ title ]
    fields:
      - name: title
        label: 标题
        type: string
      - name: tags
        label: 标签
        type: select
      - name: createTime
        label: 创建时间
        type: date
        options:
          format: yyyy-MM-dd HH:mm:ss
    